### ISSUE TITLE
No indices being built for variants

### ISSUE THREAD

**Issue by vzam** [sebischair/SimpleNLG-DE#2]
Currently the index for the variants of a word in not filled in the XMLLexicon, which is why the words in a lexicon cannot be resolved by their variants. I checked the source and the index is never being assigned to so I guess it was forgotten about. You can see it yourself when you compare [the source](https://github.com/sebischair/SimpleNLG-DE/blob/1a0756c8ab423ecd51548a50f9acba8c19fa4774/src/main/java/simplenlgde/lexicon/XMLLexicon.java#L219) with the [english variant](https://github.com/simplenlg/simplenlg/blob/47686090f52c5bf873f77fa6139c34aac1ea8ec3/src/main/java/simplenlg/lexicon/XMLLexicon.java#LL266C8-L266C8) of simpleNLG.

Here is a test in written kotlin that should succeed:
```kotlin
    @Test
    fun `noun phrase resolves word from lexicon by variant`() {
        val lexicon = Lexicon.getDefaultLexicon()
        val factory = NLGFactory(lexicon)

        val nounPhrase = factory.createNounPhrase("Menschen")

        assertEquals("Mensch", (nounPhrase.noun as WordElement).baseForm)
    }
```

**Comment by DaBr01** [comment]
Thanks for pointing this out. I will look into it.
