### ISSUE TITLE
Sentence realizer is using default lexicon

### ISSUE THREAD

**Issue by vzam** [sebischair/SimpleNLG-DE#3]
Usually I am using the default lexicon but I was also wondering about a rather large memory footprint and found a possible issue here:
https://github.com/sebischair/SimpleNLG-DE/blob/843d14e8ec2d1d080e7e6da14e8b50b2d915f464/src/main/java/simplenlgde/syntax/ClauseHelper.java#LL59C16-L59C16

The default lexicon is being initialized for the realization of a clause, but I think the lexicon from the parent should be reused instead.
I didn't test it but this could also lead to a bug where default lexicon is not being used at all for clauses.

**Comment by DaBr01** [comment]
Oh wow, this is wild. Thanks for spotting it! I noticed it myself while fixing #2 but hadn't found yet where it happens. There it is. This cuts down realisiation time by a crazy factor.

**Comment by DaBr01** [comment]
Oh wow, this is wild. Thanks for spotting it! I noticed it myself while fixing #2 but hadn't found yet where it happens. There it is. This cuts down realisiation time by a crazy factor.
